server:
  port: 666
spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/msdb?AutoReconnect=true&useSSL=false
    username: root
    password: 9o0p-[=]
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true